### ISSUE TITLE
How getdata by location?

### ISSUE THREAD

**Issue by Biangkerok32** [mew/Coronavirus#2]
Great Library Sir,,
:+1:  👍
How to call function getdata by location?

**Comment by ExpDev07** [comment]
First, locate it’s in in /locations, then access it’s data through /locations/id

**Comment by mew** [comment]
Aww thank you <3

I have just updated the wrapper to use v2 of the API so this is now possible without relying on some janky solution.

Using the most recent release (0.2.0 at time of writing), you can do it like:
```java
Coronavirus coronavirus = new Coronavirus();
Latest latestOntario = coronavirus.getLocationsByProvince("Ontario");
System.out.println("Cases in Ontario: " + latestOntario.getConfirmed());
```
