### ISSUE TITLE
Example in readme references nonexistent 'latest' variable

### ISSUE THREAD

**Issue by ethteck** [mew/Coronavirus#3]
Basically the title. It looks like that code wouldn't compile, unless I'm missing something

**Comment by josefsarkis** [comment]
Same here. Variable latest doesn't exist, code won't compile. 

> Basically the title. It looks like that code wouldn't compile, unless I'm missing something

**Comment by mew** [comment]
Yikes, good catch! [I have updated the README](https://git.io/Jv7C3).

Thank you :)
